# Generated by Django 4.2 on 2023-04-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parkingapp", "0003_remove_parkingspot_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Credit Card", "Credit Card"),
                            ("Debit Card", "Debit Card"),
                            ("Paypal", "Paypal"),
                            ("Bitcoin", "Bitcoin"),
                            ("Other", "Other"),
                        ],
                        default="Cash",
                        max_length=100,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Complete", "Complete"),
                            ("Cancelled", "Cancelled"),
                            ("Refunded", "Refunded"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                ("payment_amount", models.IntegerField()),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_id", models.IntegerField()),
                ("vehicle_license_plate", models.CharField(max_length=100)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Car", "Car"),
                            ("Truck", "Truck"),
                            ("Motorcycle", "Motorcycle"),
                            ("Van", "Van"),
                        ],
                        default="Car",
                        max_length=100,
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=100)),
                ("vehicle_model", models.CharField(max_length=100)),
                ("vehicle_color", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ParkingTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.IntegerField()),
                ("entryTime", models.DateTimeField(auto_now_add=True)),
                (
                    "entryGate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parkingapp.entrygate",
                    ),
                ),
                (
                    "entryOperator_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parkingapp.operators",
                    ),
                ),
                (
                    "parkingSpot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parkingapp.parkingspot",
                    ),
                ),
                (
                    "vehicle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_id", models.IntegerField()),
                ("exitTime", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                (
                    "exitGate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parkingapp.exitgate",
                    ),
                ),
                (
                    "exitOperator_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parkingapp.operators",
                    ),
                ),
                (
                    "parkingTicket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.parkingticket",
                    ),
                ),
                (
                    "payment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.payment",
                    ),
                ),
            ],
        ),
    ]
