# Generated by Django 4.2 on 2023-04-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="exitGate_id",
            new_name="exitGate",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="exitOperator_id",
            new_name="exitOperator",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="payment_id",
            new_name="payment",
        ),
        migrations.RenameField(
            model_name="parkingticket",
            old_name="entryGate_id",
            new_name="entryGate",
        ),
        migrations.RenameField(
            model_name="parkingticket",
            old_name="entryOperator_id",
            new_name="entryOperator",
        ),
        migrations.RenameField(
            model_name="parkingticket",
            old_name="vehicle_id",
            new_name="vehicle",
        ),
    ]
