# Generated by Django 4.2 on 2023-04-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DisplayBoard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("message", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parkingapp.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Operators",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=100)),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Active",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParkingFloor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("floor_number", models.IntegerField()),
                (
                    "floor_name",
                    models.CharField(
                        choices=[
                            ("First", "First"),
                            ("Second", "Second"),
                            ("Third", "Third"),
                            ("Fourth", "Fourth"),
                        ],
                        default="First",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parkingapp.address",
                    ),
                ),
                (
                    "parking_floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parkingapp.parkingfloor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntryGate",
            fields=[
                (
                    "gate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="parkingapp.gate",
                    ),
                ),
                (
                    "display_board",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="parkingapp.displayboard",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("parkingapp.gate",),
        ),
        migrations.CreateModel(
            name="ExitGate",
            fields=[
                (
                    "gate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="parkingapp.gate",
                    ),
                ),
                (
                    "display_board",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="parkingapp.displayboard",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("parkingapp.gate",),
        ),
        migrations.CreateModel(
            name="PaymentCounter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("counter_number", models.IntegerField()),
                ("amount", models.IntegerField()),
                (
                    "parking_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parkingapp.parkinglot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "spot_type",
                    models.CharField(
                        choices=[
                            ("Compact", "Compact"),
                            ("Large", "Large"),
                            ("Motorcycle", "Motorcycle"),
                            ("Handicapped", "Handicapped"),
                        ],
                        default="Compact",
                        max_length=100,
                    ),
                ),
                (
                    "spot_status",
                    models.CharField(
                        choices=[("Occupied", "Occupied"), ("Vacant", "Vacant")],
                        default="Vacant",
                        max_length=100,
                    ),
                ),
                (
                    "parking_floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parkingapp.parkingfloor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="gate",
            name="operators",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parkingapp.operators"
            ),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="entry_gate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parkingapp.entrygate"
            ),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="exit_gate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parkingapp.exitgate"
            ),
        ),
    ]
