# Generated by Django 4.2 on 2023-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parkingapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingfloor",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="parkingfloor",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="parkingfloor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
